# Generated by Django 5.1.6 on 2025-02-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
